#!/bin/bash

PROJECT_NAME="$1"
SCALA_VERSION="2.10.3"
SCALATEST_VERSION="1.9.2"
MOCKITO_VERSION="1.9.5"

SBT_IDEA_VERSION="1.5.2"

if [ -z $PROJECT_NAME ]; then
  echo Usage: bootstrap-scala project-name
  exit 1
fi

mkdir $PROJECT_NAME
cd $PROJECT_NAME

cat > build.sbt << EOF
name := "$PROJECT_NAME"

version := "1.0"

scalaVersion := "$SCALA_VERSION"

libraryDependencies += "org.scalatest" %% "scalatest" % "$SCALATEST_VERSION" % "test"

libraryDependencies += "org.mockito" % "mockito-core" % "$MOCKITO_VERSION" % "test"
EOF

mkdir -p "src/main/scala"
mkdir -p "src/main/java"
mkdir -p "src/main/resources"
mkdir -p "src/test/scala"
mkdir -p "src/test/java"
mkdir -p "src/test/resources"

cat > .gitignore << EOF
target/
.DS_Store
.idea
.idea_modules
EOF

git init
git add .gitignore
git add build.sbt
git commit -m 'Initial commit'


mkdir project
cat > project/plugins.sbt << EOF
addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "$SBT_IDEA_VERSION")
EOF

sbt update gen-idea