#!/bin/bash
INPUT="$1"
OUTPUT="$2"

usage() {
	echo "gif2mp4 input_file output_file"
	exit 1
}

if [ -z $INPUT ]; then usage; fi
if [ -z $OUTPUT ]; then usage; fi

ffmpeg -i $INPUT -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" $OUTPUT
