#!/bin/bash
echo "--> Downloading Internet Explorer 6-11 on Windows XP/7/8 Appliances for VMWare Fusion. Large downloads ahead.\n\n"

mkdir -p ~/Downloads/modern.ie
cd ~/Downloads/modern.ie

echo "
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE6-WinXP&filename=VMware/IE6_WinXP/Mac/IE6.WinXP.For.MacVMWare.sfx
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE7-Vista&filename=VMware/IE7_Vista/Mac/IE7.Vista.For.MacVMware.part01.sfx
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE7-Vista&filename=VMware/IE7_Vista/Mac/IE7.Vista.For.MacVMware.part02.rar
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE7-Vista&filename=VMware/IE7_Vista/Mac/IE7.Vista.For.MacVMware.part03.rar
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE7-Vista&filename=VMware/IE7_Vista/Mac/IE7.Vista.For.MacVMware.part04.rar
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE8-WinXP&filename=VMware/IE8_WinXP/Mac/IE8.WinXP.For.MacVMWare.sfx
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE9-Win7&filename=VMware/IE9_Win7/Mac/IE9.Win7.For.MacVMware.part01.sfx
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE9-Win7&filename=VMware/IE9_Win7/Mac/IE9.Win7.For.MacVMware.part02.rar
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE9-Win7&filename=VMware/IE9_Win7/Mac/IE9.Win7.For.MacVMware.part03.rar
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE9-Win7&filename=VMware/IE9_Win7/Mac/IE9.Win7.For.MacVMware.part04.rar
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE10-Win7&filename=VMware/IE10_Win7/Mac/IE10.Win7.For.MacVMware.part01.sfx
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE10-Win7&filename=VMware/IE10_Win7/Mac/IE10.Win7.For.MacVMware.part02.rar
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE10-Win7&filename=VMware/IE10_Win7/Mac/IE10.Win7.For.MacVMware.part03.rar
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE11-Win7&filename=VMware/IE11_Win7/Mac/IE11.Win7.For.MacVMware.part01.sfx
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE11-Win7&filename=VMware/IE11_Win7/Mac/IE11.Win7.For.MacVMware.part02.rar
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE11-Win7&filename=VMware/IE11_Win7/Mac/IE11.Win7.For.MacVMware.part03.rar
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE11-Win8.1&filename=VMware/IE11_Win8.1/Mac/IE11.Win8.1.For.MacVMware.part1.sfx
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE11-Win8.1&filename=VMware/IE11_Win8.1/Mac/IE11.Win8.1.For.MacVMware.part2.rar
http://www.modern.ie/vmdownload?platform=mac&virtPlatform=vmware&browserOS=IE11-Win8.1&filename=VMware/IE11_Win8.1/Mac/IE11.Win8.1.For.MacVMware.part3.rar
" > /tmp/modernie-urls.txt

aria2c -s4 -i/tmp/modernie-urls.txt

exit
