#!/bin/sh
# Pinentry wrapper for 1Password
# Based on: https://gist.github.com/mrgrain/9c3519952d9af811bd7bf50bfcfaa16f

OP_PGP_KEY_ID="${OP_PGP_KEY_ID:-b2lpibkkqfqtp5lvvp25ugx3kq}"
OP_PIN_ITEM="${OP_PIN_ITEM:-op://Private/$OP_PGP_KEY_ID/password}"

# Command to get password from 1Password
COMMAND="op read $OP_PIN_ITEM"

# Respond OK immediately (required by pinentry protocol)
        echo "OK"

# Read commands from stdin
while read -r cmd rest; do
  case "$cmd" in
    \#*)
      echo "OK"
      ;;
    GETPIN)
      PASSPHRASE=${PASSPHRASE:-$(eval "$COMMAND" 2>/dev/null)}
      echo "D ${PASSPHRASE}"
      echo "OK"
      ;;
    BYE)
      echo "OK"
      exit 0
      ;;
    *)
      echo "OK"
      ;;
  esac
done

