#!/bin/bash
SESSION_NAME=$1
if [[ -z "$SESSION_NAME" ]]; then SESSION_NAME=0; fi

if tmux has -t "$SESSION_NAME" 2>/dev/null; then
  tmux attach -t "$SESSION_NAME"
else
  tmux new -s "$SESSION_NAME"
fi
