#!/bin/bash
if which avconv >/dev/null; then
  CMD='avconv'
else
  CMD='ffmpeg'
fi

RESULT=`AV_LOG_FORCE_NO_COLOR=true $CMD -v warning -i "$1" -acodec copy -vcodec copy -f null - 2>&1`
if [ -z "$RESULT" ] ; then
  echo "ok"
  exit 0
else
  echo "$RESULT"
  exit 1
fi
